model_runner:
  version: v2

python:
  version: 3.5.9

model:
  name: 扫描git敏感信息
  version: v0.0.1

apis:
  - endpoint: /api/model
    http_method: POST
    body:
      method: find_secret
      kwargs:
        git_url: str  # 目标git仓库地址
    response:
      status: str  # ok|err
      value: int  # 隐私扫描结果 或 错误描述
