model_runner:
  version: v2

python:
  version: 3.5.9

model:
  name: 手写数字识别
  version: v0.0.1

apis:
  - endpoint: /api/model
    http_method: POST
    body:
      method: gen_test_img_base64
      kwargs:
    response:
      status: str  # ok|err
      value: str  # 压缩图像的base64编码字符串 或 错误描述
  - endpoint: /api/model
    http_method: POST
    body:
      method: gen_test_img_bin
      kwargs:
    response: bytes  # 二进制编码的压缩图像字节流
  - endpoint: /api/model
    http_method: POST
    body:
      method: classify_base64
      kwargs:
        img_base64: str  # 压缩图像的base64编码字符串
    response:
      status: str  # ok|err
      value: int  # 手写数字识别结果 或 错误描述
  - endpoint: /api/stream/classify_base64
    http_method: POST
    body: bytes  # 二进制编码的压缩图像字节流
    response:
      status: str  # ok|err
      value: int  # 手写数字识别结果 或 错误描述
  - endpoint: /api/file/classify_base64
    http_method: POST
    body: XHR  # XMLHttpRequest，用于HTTP文件上传
    response:
      status: str  # ok|err
      value: int  # 手写数字识别结果 或 错误描述
