model_runner:
  version: v2

python:
  version: 3.6.9

model:
  name: 手绘照片
  version: v0.0.1

apis:
  - endpoint: /api/model
    http_method: POST
    body:
      method: photo2painter_base64
      kwargs:
        img_base64: str  # 压缩图像的base64编码字符串
    response:
      status: str  # ok|err
      value: list  # [<手绘照片过程的base64编码URL字符串>, ...]
  - endpoint: /api/model
    http_method: POST
    body:
      method: gen_test_img_base64
      kwargs:
    response:
      status: str  # ok|err
      value: str  # 压缩图像的base64编码字符串 或 错误描述
